#!/bin/bash

python scrabble_hierarchy.py learn -bl ebu3b,ap_m -nl 200,1 -c true &
python scrabble_hierarchy.py learn -bl ebu3b,ap_m -nl 200,5 -c true &
python scrabble_hierarchy.py learn -bl ebu3b,ap_m -nl 200,20 -c true &
python scrabble_hierarchy.py learn -bl ebu3b,ap_m -nl 200,50 -c true &
python scrabble_hierarchy.py learn -bl ebu3b,ap_m -nl 200,200 -c true &
