#!/home/jbkoh/anaconda3/bin/python

import os
import time

n_list = [200]
target_n_list = [50]
#n_list = [50, 100, 200]
#target_n_list = [10, 50]
building_list = ['ebu3b', 'ap_m']
cluster_flag_list = [True]

for source_building in building_list:
    for target_building in building_list:
        for cluster_flag in cluster_flag_list:
            for n in n_list:
                os.system('python scrabble.py predict -bl {0} -nl {1} -c {2} -t {3}&'\
                        .format(source_building, n, cluster_flag, target_building))
                if source_building==target_building:
                    continue
                for sub_n in target_n_list:
                    os.system('python scrabble.py predict -bl {0},{1} -nl {2},{3} -c {4} -t {1} &'\
                            .format(source_building, target_building, n, sub_n, cluster_flag))
