#!/bin/bash


python naive_baseline.py -bl ebu3b,ap_m -t ap_m -nl 200,0 -avg 4
python naive_baseline.py -bl ap_m,bml -t bml -nl 200,0 -avg 4
python naive_baseline.py -bl ebu3b,ghc -t ghc -nl 200,0 -avg 4
python naive_baseline.py -bl ghc,ebu3b -t ebu3b -nl 200,0 -avg 4
python naive_baseline.py -bl ebu3b,bml,ap_m -t ap_m -nl 200,200,0 -avg 4
python naive_baseline.py -bl ebu3b,bml,ap_m -t ap_m -nl 200,200,0 -avg 4
