#!/home/jbkoh/anaconda3/bin/python

import os

from crf_trainer_char_level import crf_test


n_list = [50, 100, 200]
building_list = ['ap_m', 'ebu3b']
cluster_flag_list = [False, True]

for n in n_list:
    for source_building in building_list:
        for target_building in building_list:
            for cluster_flag in cluster_flag_list:
                os.system('python crf_trainer_char_level.py predict -b {0} -t {1} -n {2} -c {3} &'\
                        .format(source_building, target_building, n, cluster_flag))
